#!/bin/sh

ENABLED=yes

DESC="NTP with NTS server"
PROCS="ntp-daemon"
PROG="/opt/usr/bin/$PROCS"

pre_cmd() {
  [ -d "/opt/var/run/ntpd-rs" ] || mkdir -pm 0755 /opt/var/run/ntpd-rs
}

PRECMD="pre_cmd"
ARGS=""
PREARGS=""

. /opt/etc/init.d/rc.func
